# Generated by Django 5.2.3 on 2025-08-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roadmap',
            name='duration_weeks',
        ),
        migrations.RemoveField(
            model_name='roadmap',
            name='level',
        ),
        migrations.AddField(
            model_name='roadmap',
            name='icon',
            field=models.CharField(default='🌐', max_length=50),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
