# Generated by Django 5.2.3 on 2025-08-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_roadmap_duration_weeks_remove_roadmap_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmap',
            name='duration_weeks',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='roadmaps/'),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='learners_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('All Levels', 'All Levels')], default='Beginner', max_length=50),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roadmap',
            name='tutorial_count',
            field=models.IntegerField(default=0),
        ),
    ]
